# Generated by Django 4.2.16 on 2026-07-14 10:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_content', models.JSONField(default=dict)),
                ('declare_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批复')], default='draft', max_length=20)),
                ('external_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flight_plan',
            },
        ),
        migrations.CreateModel(
            name='OrderMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_match_log',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pilot_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('holding', '托管中'), ('paid', '已打款'), ('refunded', '已退款')], default='holding', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settlement',
            },
        ),
        migrations.CreateModel(
            name='WorkMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=10)),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_media',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('work_type', models.CharField(choices=[('plant', '植保'), ('inspect', '巡检'), ('aerial', '航拍'), ('survey', '测绘')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('execute_time', models.DateTimeField()),
                ('area_or_duration', models.CharField(max_length=64)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('license_req', models.CharField(blank=True, default='', max_length=64)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '待匹配'), ('matched', '已推送'), ('accepted', '已接单'), ('declared', '已申报'), ('working', '作业中'), ('submitted', '待验收'), ('accepted_done', '已验收'), ('settled', '已结算'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('match_radius_km', models.FloatField(default=50)),
                ('assigned_by_admin', models.BooleanField(default=False)),
                ('platform_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='orders.workorder')),
            ],
            options={
                'db_table': 'work_track',
                'ordering': ['recorded_at'],
            },
        ),
    ]
