# Generated by Django 4.2.16 on 2026-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workorder',
            name='custom_work_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='自定义作业类型'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='district',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workorder',
            name='province',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workorder',
            name='region_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='行政区划代码'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('plant', '植保'), ('inspect', '巡检'), ('aerial', '航拍'), ('survey', '测绘'), ('logistics', '物流配送'), ('emergency', '应急救援'), ('security', '安防监控'), ('show', '表演航展'), ('training', '培训考试'), ('other', '其它自定义')], max_length=32),
        ),
    ]
