# Generated by Django 4.2.16 on 2026-07-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_rate', models.DecimalField(decimal_places=4, default=0.12, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', '待结算'), ('paid', '已结算')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agency_fee',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('interview_invite', '面试邀约')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('recommended', 'AI推荐'), ('applied', '已投递'), ('interview', '面试中'), ('offered', '已发Offer'), ('hired', '已入职'), ('rejected', '已拒绝')], default='applied', max_length=20)),
                ('source', models.CharField(choices=[('self', '主动投递'), ('ai', 'AI推荐')], default='self', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('job_type', models.CharField(choices=[('fulltime', '全职'), ('parttime', '长期兼职')], default='fulltime', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('license_req', models.CharField(blank=True, default='', max_length=64)),
                ('benefits', models.TextField(blank=True, default='')),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', '招聘中'), ('closed', '已关闭')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_url', models.URLField(blank=True, default='')),
                ('contract_content', models.TextField(blank=True, default='')),
                ('signed_enterprise', models.BooleanField(default=False)),
                ('signed_pilot', models.BooleanField(default=False)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'labor_contract',
            },
        ),
    ]
