# Generated by Django 4.2.16 on 2026-07-14 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', '可租'), ('rented', '出租中'), ('maintaining', '维保中')], default='available', max_length=20)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drone_device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintained_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'maintenance_record',
                'ordering': ['-maintained_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('pickup', '线下自提'), ('express', '物流配送')], default='pickup', max_length=20)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_waived', models.BooleanField(default=False)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending_pay', '待支付'), ('renting', '租赁中'), ('returning', '归还核验中'), ('settled', '已结清'), ('cancelled', '已取消')], default='pending_pay', max_length=20)),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_score_snapshot', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='rental.dronedevice')),
            ],
            options={
                'db_table': 'rental_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
